export interface Survey {
    id: string,
    name: string,
    email: string,
    howDidYougetToKnowUs: string,
    internet?: string,
    usageDuration: string,
    rate: string,
    purchaseLocation: string,
    purchaseReason: string,
    angelsEye: string,
    issues: string,
    benefits: string,
    ageGroup: string,
    occupationAndImpact: string,
    customerService: string,
    suggestionsOnCustomerService?: string,
    county: string,
    noticeOfBrand: string,
    suggestionsOnProductImprovememnt: string,
    nextProductOrService: string,
    wouldRecommend: string,
    wouldTakeSurveyAgain: string,
}
